//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPAStudio.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RPAStudio.Localization.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 活动 的本地化字符串。
        /// </summary>
        public static string dock_activities {
            get {
                return ResourceManager.GetString("dock_activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码片段 的本地化字符串。
        /// </summary>
        public static string dock_code_snippets {
            get {
                return ResourceManager.GetString("dock_code_snippets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大纲 的本地化字符串。
        /// </summary>
        public static string dock_outline {
            get {
                return ResourceManager.GetString("dock_outline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出 的本地化字符串。
        /// </summary>
        public static string dock_output {
            get {
                return ResourceManager.GetString("dock_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目 的本地化字符串。
        /// </summary>
        public static string dock_projects {
            get {
                return ResourceManager.GetString("dock_projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性 的本地化字符串。
        /// </summary>
        public static string dock_properties {
            get {
                return ResourceManager.GetString("dock_properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新 的本地化字符串。
        /// </summary>
        public static string help_check_for_update_btn_text {
            get {
                return ResourceManager.GetString("help_check_for_update_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在检查更新 的本地化字符串。
        /// </summary>
        public static string help_checking_for_update_btn_text {
            get {
                return ResourceManager.GetString("help_checking_for_update_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载更新 的本地化字符串。
        /// </summary>
        public static string help_download_btn_text {
            get {
                return ResourceManager.GetString("help_download_btn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前为最新版本，无需升级！ 的本地化字符串。
        /// </summary>
        public static string help_no_need_to_update {
            get {
                return ResourceManager.GetString("help_no_need_to_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中断 的本地化字符串。
        /// </summary>
        public static string main_break {
            get {
                return ResourceManager.GetString("main_break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常时中断 的本地化字符串。
        /// </summary>
        public static string main_break_on_exceptions {
            get {
                return ResourceManager.GetString("main_break_on_exceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中断执行（暂停） 的本地化字符串。
        /// </summary>
        public static string main_break_tip {
            get {
                return ResourceManager.GetString("main_break_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 断点 的本地化字符串。
        /// </summary>
        public static string main_breakpoint {
            get {
                return ResourceManager.GetString("main_breakpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string main_close {
            get {
                return ResourceManager.GetString("main_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        public static string main_copy {
            get {
                return ResourceManager.GetString("main_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剪切 的本地化字符串。
        /// </summary>
        public static string main_cut {
            get {
                return ResourceManager.GetString("main_cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调试 的本地化字符串。
        /// </summary>
        public static string main_debug {
            get {
                return ResourceManager.GetString("main_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 依赖 的本地化字符串。
        /// </summary>
        public static string main_dependency {
            get {
                return ResourceManager.GetString("main_dependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部署 的本地化字符串。
        /// </summary>
        public static string main_deploy {
            get {
                return ResourceManager.GetString("main_deploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设计 的本地化字符串。
        /// </summary>
        public static string main_design {
            get {
                return ResourceManager.GetString("main_design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string main_edit {
            get {
                return ResourceManager.GetString("main_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行 的本地化字符串。
        /// </summary>
        public static string main_execution {
            get {
                return ResourceManager.GetString("main_execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        public static string main_file {
            get {
                return ResourceManager.GetString("main_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程图 的本地化字符串。
        /// </summary>
        public static string main_flowchart {
            get {
                return ResourceManager.GetString("main_flowchart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助 的本地化字符串。
        /// </summary>
        public static string main_help {
            get {
                return ResourceManager.GetString("main_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高亮元素 的本地化字符串。
        /// </summary>
        public static string main_highlight_elements {
            get {
                return ResourceManager.GetString("main_highlight_elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在加载…… 的本地化字符串。
        /// </summary>
        public static string main_loading {
            get {
                return ResourceManager.GetString("main_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录活动 的本地化字符串。
        /// </summary>
        public static string main_log_activities {
            get {
                return ResourceManager.GetString("main_log_activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志 的本地化字符串。
        /// </summary>
        public static string main_logs {
            get {
                return ResourceManager.GetString("main_logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建 的本地化字符串。
        /// </summary>
        public static string main_new {
            get {
                return ResourceManager.GetString("main_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        public static string main_open {
            get {
                return ResourceManager.GetString("main_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开日志 的本地化字符串。
        /// </summary>
        public static string main_open_logs {
            get {
                return ResourceManager.GetString("main_open_logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开日志（Ctrl+L） 的本地化字符串。
        /// </summary>
        public static string main_open_logs_tip {
            get {
                return ResourceManager.GetString("main_open_logs_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string main_operation {
            get {
                return ResourceManager.GetString("main_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项 的本地化字符串。
        /// </summary>
        public static string main_options {
            get {
                return ResourceManager.GetString("main_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包管理器 的本地化字符串。
        /// </summary>
        public static string main_package_manager {
            get {
                return ResourceManager.GetString("main_package_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理nupkg包，实现安装、卸载、更新包等操作（Ctrl+P） 的本地化字符串。
        /// </summary>
        public static string main_package_manager_tip {
            get {
                return ResourceManager.GetString("main_package_manager_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘贴 的本地化字符串。
        /// </summary>
        public static string main_paste {
            get {
                return ResourceManager.GetString("main_paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发布 的本地化字符串。
        /// </summary>
        public static string main_publish {
            get {
                return ResourceManager.GetString("main_publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打包发布 的本地化字符串。
        /// </summary>
        public static string main_publish_tip {
            get {
                return ResourceManager.GetString("main_publish_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录制 的本地化字符串。
        /// </summary>
        public static string main_recording {
            get {
                return ResourceManager.GetString("main_recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一次性录制多个活动 的本地化字符串。
        /// </summary>
        public static string main_recording_tip {
            get {
                return ResourceManager.GetString("main_recording_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除所有断点 的本地化字符串。
        /// </summary>
        public static string main_remove_all_breakpoints {
            get {
                return ResourceManager.GetString("main_remove_all_breakpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除所有断点（Shift+F9） 的本地化字符串。
        /// </summary>
        public static string main_remove_all_breakpoints_tip {
            get {
                return ResourceManager.GetString("main_remove_all_breakpoints_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行 的本地化字符串。
        /// </summary>
        public static string main_run {
            get {
                return ResourceManager.GetString("main_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行（F5） 的本地化字符串。
        /// </summary>
        public static string main_run_tip {
            get {
                return ResourceManager.GetString("main_run_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string main_save {
            get {
                return ResourceManager.GetString("main_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部保存 的本地化字符串。
        /// </summary>
        public static string main_save_all {
            get {
                return ResourceManager.GetString("main_save_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部保存（Ctrl+Shift+S） 的本地化字符串。
        /// </summary>
        public static string main_save_all_tip {
            get {
                return ResourceManager.GetString("main_save_all_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 另存为 的本地化字符串。
        /// </summary>
        public static string main_save_as {
            get {
                return ResourceManager.GetString("main_save_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存（Ctrl+S） 的本地化字符串。
        /// </summary>
        public static string main_save_tip {
            get {
                return ResourceManager.GetString("main_save_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序列图 的本地化字符串。
        /// </summary>
        public static string main_sequence {
            get {
                return ResourceManager.GetString("main_sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序列图（Ctrl+N） 的本地化字符串。
        /// </summary>
        public static string main_sequence_tip {
            get {
                return ResourceManager.GetString("main_sequence_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string main_settings {
            get {
                return ResourceManager.GetString("main_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 慢速调试 的本地化字符串。
        /// </summary>
        public static string main_slow_debugging {
            get {
                return ResourceManager.GetString("main_slow_debugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以最慢的1x到最快4x进行不同速度的调试运行 的本地化字符串。
        /// </summary>
        public static string main_slow_debugging_tip {
            get {
                return ResourceManager.GetString("main_slow_debugging_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始 的本地化字符串。
        /// </summary>
        public static string main_start {
            get {
                return ResourceManager.GetString("main_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 的本地化字符串。
        /// </summary>
        public static string main_start_up {
            get {
                return ResourceManager.GetString("main_start_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态机 的本地化字符串。
        /// </summary>
        public static string main_state_machine {
            get {
                return ResourceManager.GetString("main_state_machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 逐语句 的本地化字符串。
        /// </summary>
        public static string main_step_into {
            get {
                return ResourceManager.GetString("main_step_into", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 逐语句（F11） 的本地化字符串。
        /// </summary>
        public static string main_step_into_tip {
            get {
                return ResourceManager.GetString("main_step_into_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 逐过程 的本地化字符串。
        /// </summary>
        public static string main_step_over {
            get {
                return ResourceManager.GetString("main_step_over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 逐过程（F10） 的本地化字符串。
        /// </summary>
        public static string main_step_over_tip {
            get {
                return ResourceManager.GetString("main_step_over_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        public static string main_stop {
            get {
                return ResourceManager.GetString("main_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止（F12） 的本地化字符串。
        /// </summary>
        public static string main_stop_tip {
            get {
                return ResourceManager.GetString("main_stop_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换断点 的本地化字符串。
        /// </summary>
        public static string main_toggle_breakpoint {
            get {
                return ResourceManager.GetString("main_toggle_breakpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换断点（F9） 的本地化字符串。
        /// </summary>
        public static string main_toggle_breakpoint_tip {
            get {
                return ResourceManager.GetString("main_toggle_breakpoint_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新 的本地化字符串。
        /// </summary>
        public static string main_update {
            get {
                return ResourceManager.GetString("main_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校验 的本地化字符串。
        /// </summary>
        public static string main_validate {
            get {
                return ResourceManager.GetString("main_validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查错误（F8） 的本地化字符串。
        /// </summary>
        public static string main_validate_tip {
            get {
                return ResourceManager.GetString("main_validate_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新 的本地化字符串。
        /// </summary>
        public static string settings_check_update {
            get {
                return ResourceManager.GetString("settings_check_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除缓存 的本地化字符串。
        /// </summary>
        public static string settings_clear_cache {
            get {
                return ResourceManager.GetString("settings_clear_cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设计 的本地化字符串。
        /// </summary>
        public static string settings_design {
            get {
                return ResourceManager.GetString("settings_design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常规 的本地化字符串。
        /// </summary>
        public static string settings_general {
            get {
                return ResourceManager.GetString("settings_general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        public static string settings_language {
            get {
                return ResourceManager.GetString("settings_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更改 Studio 界面显示语言（重启后生效） 的本地化字符串。
        /// </summary>
        public static string settings_language_tip {
            get {
                return ResourceManager.GetString("settings_language_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nuget 相关设置 的本地化字符串。
        /// </summary>
        public static string settings_nuget_tip {
            get {
                return ResourceManager.GetString("settings_nuget_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他 的本地化字符串。
        /// </summary>
        public static string settings_other {
            get {
                return ResourceManager.GetString("settings_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更改软件其他设置 的本地化字符串。
        /// </summary>
        public static string settings_other_tip {
            get {
                return ResourceManager.GetString("settings_other_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题 的本地化字符串。
        /// </summary>
        public static string settings_theme {
            get {
                return ResourceManager.GetString("settings_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更改 Studio 界面主题 的本地化字符串。
        /// </summary>
        public static string settings_theme_tip {
            get {
                return ResourceManager.GetString("settings_theme_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        public static string settings_upgrade {
            get {
                return ResourceManager.GetString("settings_upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从最近列表中移除此项 的本地化字符串。
        /// </summary>
        public static string start_delete_tip {
            get {
                return ResourceManager.GetString("start_delete_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建项目 的本地化字符串。
        /// </summary>
        public static string start_newproject {
            get {
                return ResourceManager.GetString("start_newproject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程 的本地化字符串。
        /// </summary>
        public static string start_newproject_process {
            get {
                return ResourceManager.GetString("start_newproject_process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建一个自动化的空白流程 的本地化字符串。
        /// </summary>
        public static string start_newproject_process_tip {
            get {
                return ResourceManager.GetString("start_newproject_process_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        public static string start_open {
            get {
                return ResourceManager.GetString("start_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开项目所在目录 的本地化字符串。
        /// </summary>
        public static string start_opendir_tip {
            get {
                return ResourceManager.GetString("start_opendir_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开本地项目 的本地化字符串。
        /// </summary>
        public static string start_openproject {
            get {
                return ResourceManager.GetString("start_openproject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览并打开现有项目 的本地化字符串。
        /// </summary>
        public static string start_openproject_tip {
            get {
                return ResourceManager.GetString("start_openproject_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开最近的内容 的本地化字符串。
        /// </summary>
        public static string start_openrecent {
            get {
                return ResourceManager.GetString("start_openrecent", resourceCulture);
            }
        }
    }
}
